### ISSUE TITLE
No window with title "Results" found

### ISSUE THREAD

**Issue by BasVD23** [ADanckaert/MuscleJ#1]
![Bug](https://user-images.githubusercontent.com/128596252/226886946-09ce56bb-ec57-43fa-b714-d3c0026af964.png)

Hi!

The bug happens when I enter all the settings and it's starts computing. I've followed the manual but this is a fault that keeps happening. I've set everything in the same file already, thought maybe that would help but it didn't. 

Anyone knows what I am doing wrong? 

Thanks!

**Comment by Felipe-Leite** [comment]
Same error here

**Comment by ramikheireddine** [comment]
Any solutions for this error? I am having the same error.

**Comment by ADanckaert** [comment]
Dear all

this version is no longer maintained and outdated!!!! Please use the new MuscleJ2 plugin.

Best regards
Dr Anne Danckaert
